config/routes.rb
Rails.application.routes.draw do
  post '/posts' => 'posts#create', as: :posts
  get '/posts/new' => 'posts#new', as: :new_posts
  get '/posts/index' => 'posts#index', as: :posts_index
  get '/posts/:id' => 'posts#show', as: :show_posts
  root 'posts#index'
  # resource :posts, only: [:create, :new, :index]

  post '/users' => 'users#create', as: :users
  get 'users/new' => 'users#new', as: :new_user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  # has_secure_password
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :check_logged_in, only: [:new, :create]

  def index
    @posts = Post.all
  end

  # def new
  #   @post = Post.new
  # end

  def create
    @post = Post.new(post_params)

    @post.save!
    redirect_to show_posts_path(@post.id)
  end

  def show
    @article = Article.find_by(id: params[:id])
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(params[:user])

    @user.save
    redirect_to @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.erb
<div class="nav">
  <%= link_to("New post", new_posts_path) %>
  <%= link_to("Register", new_user_path) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/nav" %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All the posts on this website can be seen below</h1>

<ul>
  <% @posts.each do |post| %>
  <li> <%= post.title %></li>
  <ul><li> <%= post.body %> </li></ul>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>Create a new post!</h1>

<%= form_for :post, url: posts_path do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>